image: python:3.6

stages:
  - unittest

test:
  stage: unittest
  script:
    - pip3.6 install --upgrade pip
    - pip3.6 install -e ".[dev]"
    - pip3.6 install pytest
    - pytest --cov=skedulord


frontend:
  stage: unittest
  script:
    - pip3.6 install --upgrade pip
    - pip3.6 install -e .
    - curl -sL https://deb.nodesource.com/setup_10.x | bash
    - apt install nodejs
    - npm install
    - lord setup --name logger --wait 1 --attempts 3
    - lord run pyjob1 "python jobs/badpyjob.py" --wait 1
    - lord run pyjob1 "python jobs/badpyjob.py" --wait 1
    - lord run pyjob1 "python jobs/pyjob.py" --wait 1
    - lord run pyjob2 "python jobs/pyjob.py" --wait 1
    - lord run pyjob2 "python jobs/pyjob.py" --wait 1
    - skedulord serve & ./node_modules/.bin/cypress run
